version: '2.4'
services:
    em-postgres:
        container_name: em-postgres
        image: postgres:15.6-alpine3.19
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: em
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - 31502:5432
        volumes:
            - em-postgres-volume:/var/lib/postgresql/data
        mem_limit: 256m
volumes:
    em-postgres-volume:
        name: em-postgres-volume
